language: node_js
node_js:
  - 8
before_script:
  - yarn install
script:
  - yarn test
  - yarn build
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
